# Generated by Django 4.2.11 on 2024-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usernameComputrabajo', models.CharField(max_length=100)),
                ('usernameInstagram', models.CharField(max_length=100)),
                ('usernameFacebook', models.CharField(max_length=100)),
                ('usernameTwitter', models.CharField(max_length=100)),
            ],
        ),
    ]
