# Generated by Django 4.2.11 on 2024-04-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instagram', models.JSONField(blank=True, null=True)),
                ('twitter', models.JSONField(blank=True, null=True)),
                ('facebook', models.JSONField(blank=True, null=True)),
                ('computrabajo', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
