# Generated by Django 4.2.11 on 2024-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_webscraping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usernameComputrabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usernameFacebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usernameInstagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usernameTwitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
