# Generated by Django 4.2.11 on 2024-04-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_empresa_usernametwitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscraping',
            name='twitter',
        ),
    ]
