# Generated by Django 4.2.11 on 2024-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_empresa_usernameacercade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usernameAcercaDe',
        ),
        migrations.AddField(
            model_name='webscraping',
            name='acercaDe',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
