# Generated by Django 4.2.11 on 2024-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_remove_empresa_usernameacercade_webscraping_acercade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscraping',
            name='acercaDe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
