# Generated by Django 4.2.11 on 2024-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_webscraping_acercade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscraping',
            name='acercaDe',
            field=models.TextField(null=True),
        ),
    ]
